### ISSUE TITLE
Better logging mechanism

### ISSUE THREAD

**Issue by LoicGrobol** [UppsalaNLP/uuparser#18]
Here I go again 🙂

For now logging is done directly via `print` calls which makes it hard to embed the parser in another application or to add a `--quiet` option…
Would you be open to a PR that changes that to proper logging calls? Preferably with [loguru](https://github.com/Delgan/loguru), which has a nice API, but if adding a dependency is somehow an issue it can be done with the clunkier `logging` from stdlib.

Also if these issues become too annoying or too time-consuming at some point do tell me!

**Comment by mdelhoneux** [comment]
Omg Loic you're just going to go through my backlog of things I never take the time to do? This would be great!!!

**Comment by mdelhoneux** [comment]
PS sorry for the delay in replying, somehow I don't always get notifications, will try to change that

**Comment by LoicGrobol** [comment]
Haha, it's just that I kinda need this change to make my experimental glue code easier and since I make them anyway, it seems better to upstream them. I will keep them coming.

**Comment by mdelhoneux** [comment]
very much appreciated!
