### ISSUE TITLE
Low UAS and LAS scores

### ISSUE THREAD

**Issue by Eugen2525** [UppsalaNLP/uuparser#2]
I have tried using your parser to test with EWT English treebank, and surprisingly UAS and LAS scores are low, around 88.50 and 85.53. I have used conll2017 shared task pretrained word embeddings. Do you think this is normal or am I doing something wrong?

**Comment by jnivre** [comment]
We had around 81.5 LAS on EWT in the CoNLL shared task 2018, but that was with predicted segmentation and postags, so your results sound reasonable if you used gold segmentation and possibly also gold tags. Keep in mind that EWT is both smaller and noisier than WSJ, so you can’t expect to see LAS scores in the 90s. The best system in the CoNLL shared task 2018 had around 84 LAS with predicted segmentation and postags.

**Comment by Eugen2525** [comment]
Thanks for the response, this explains it then. Was positively surprised to receive response from J. Nivre after reading many papers from the author of maltparser :)))
