### ISSUE TITLE
Continue training on model

### ISSUE THREAD

**Issue by vlangloisx3** [UppsalaNLP/uuparser#25]
I've been having some issues with the --continueParams option. The code that I am using to continue training a model is below:

`uuparser --outdir ewt_output --datadir ud-treebanks-v2.6 --include "en_ewt" --continue --continueParams=params.pickle`

My assumption is that the params file is in the same folder as the outdir, but I get the error: `No such file or directory: 'params.pickle'`. I've also tried inserting the actual path, but get the error: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`.

Since neither of these seem to work, where does the Params file need to be in order to load it? 

Thanks!
Val

**Comment by LoicGrobol** [comment]
Hi ! Can you paste the command line you used when using the actual path and the traceback for the `UnicodeDecodeError`?

**Comment by vlangloisx3** [comment]
Sure! Here is the command line I used when using the path:
`uuparser --outdir ewt_output --datadir ud-treebanks-v2.6 --include "en_ewt" --continue 
--continueParams=/Users/vlanglois/Desktop/project/ewt_output/en_ewt/params.pickle`

and here is the traceback:
`Traceback (most recent call last):
  File "/Library/anaconda3/bin/uuparser", line 8, in <module>
    sys.exit(main())
  File "/Library/anaconda3/lib/python3.7/site-packages/uuparser/parser.py", line 279, in main
    run(experiment,options)
  File "/Library/anaconda3/lib/python3.7/site-packages/uuparser/parser.py", line 36, in run
    stored_vocab, stored_options = pickle.load(paramsfp)
  File "/Library/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

**Comment by LoicGrobol** [comment]
(Sorry for the latency, I am really low-bandwidth on uuparser right now but I'll try to fix this :-)

Can you try installing from the master branch (using `pip install git+https://github.com/UppsalaNLP/uuparser`)? There were some changes since the last release, which I suspect won't make a difference for this but it wouldn't hurt to be sure and at least we'd have up-to-date line numbers this way

**Comment by vlangloisx3** [comment]
I'm still getting the same error even after installing from the fixup branch. It could be something wrong on my end though.

(Thanks for taking the time to look into it!)

**Comment by LoicGrobol** [comment]
Oh, if you installed with the exact command I posted in an env where uuparser is already installed, it might not have been updated because I forgot the `-U` flag, could you retry with `pip install -U git+https://github.com/UppsalaNLP/uuparser@fix-25`? Sorry for the inconvenience

**Comment by vlangloisx3** [comment]
Yes that solved the issue! Thank you so much!

**Comment by LoicGrobol** [comment]
Great, I'll merge the fix and push a release before the end of the week, then. Thank you for catching this one :-)

**Comment by LoicGrobol** [comment]
Closed by #26
