### ISSUE TITLE
Problem with extended feature set (rlMostFlag)

### ISSUE THREAD

**Issue by afalenska** [UppsalaNLP/uuparser#9]
Hi,

I think there is a problem with the extended feature set. I found this out when I was using the default options: headFlag and rlMostFlag. But when I trained my models the accuracy was always only slightly different from the models which used the minimal feature set.

So I did some debugging. I found that the extended features are always filled with paddingVec. So for example, in the function ArcHybridLSTM.__evaluate the value topStack[0] is always:
[ wordVec, paddingVec, paddingVec ] 

and never:
[ wordVec, leftWordVec, rightWordVec ]

It is like this because of the line 349 in arc_hybrid.py:
(349) root.lstms += [self.feature_extractor.paddingVec for _ in range(self.nnvecs - hoffset)]

The default value for L/R child is paddingVec. And as the features are filled recursively (line 151) they always end up using paddingVec. In the original code it used to be:
(316) root.lstms = [root.vec for _ in xrange(self.nnvecs)]
so there was no problem.

Cheers,
Agnieszka

**Comment by mdelhoneux** [comment]
Oups, you are correct! Fixed by cb3a8e77dad17182f9d78873480cd453852484af
